#### Numpy configuration and version of  numpy

In [2]:
import numpy as np
print("version: ",np.__version__)#gives version we are working with
print("configuration: \n\n",np.show_config())# gives configuration

version:  1.16.5
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Priya/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Priya/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Priya/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\

#### Add , subtract, normal multiplication, matrix multiplication

In [7]:
import numpy as np
g=[1,2,3,4,5]
a=np.array(g)
b=np.array([6,7,8,9,10])
print(a+b,'\n',a-b,'\n',a*b)
print("matrix product",np.dot(a,b))
print("type: ",type(a))

[ 7  9 11 13 15] 
 [-5 -5 -5 -5 -5] 
 [ 6 14 24 36 50]
matrix product 130
type:  <class 'numpy.ndarray'>


#### check whether all the numbers are non zero in an array

In [14]:
al=np.array([[1,2,3,4],[5,6,7,8]])
print(al.all())#array.all() is a function to check all values in array are true or false
al=np.array([[1,2,0,4],[5,6,7,8]])
print(al.all())

True
False


##### check whether an array has all element in it i.e non null, non infinite

In [16]:
i=np.array([[1,2,np.nan,4],[5,np.inf,7,8]])
print(np.isfinite(i))#numpy.isfinite(array) returns true if all the values are true i.e. non infinite,NaN

[[ True  True False  True]
 [ True False  True  True]]


#### to find Nan values

In [17]:
print(np.isnan(i)) #numpy.isnan(array) returns true where ever the value are NaN else returns false

[[False False  True False]
 [False False False False]]


#### create arrays full of zeros, ones, or with single number

In [8]:
m=(3,4)
z=np.zeros(m)#numpy.zeros(row,col)=>produces array full of 0s.
o=np.ones(m)#numpy.ones(row,col)=>produces array full of 1s.
n=np.full((m),8)#numpy.full((row,col),element)=>produces array full of elements.
print(z)
print(o)
print(n)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


#### create an array with range of numbers

In [17]:
ar=np.arange(20,50).reshape(5,6)#numpy.arange(start,end)=>produces a matrix with element between the range
print(ar)#"""reshape(row,col) where row,col should be a factor of range of 
# numbers e.g here (20,50=>50-20=30; row,col=>(6,5),(5,6),(30,1)etc)"""

[[20 21 22 23 24 25]
 [26 27 28 29 30 31]
 [32 33 34 35 36 37]
 [38 39 40 41 42 43]
 [44 45 46 47 48 49]]


#### identity matrix 

In [27]:
im=np.identity(7)
print(im)#numpy.identity(dimension) produces identity matrix of dimension*dimension

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


#### random function

In [42]:
from numpy import random
print("list of random 8 numbers",random.rand(8))# prints 8 random numbers
print("number between 0,1",random.normal(0,1,1))#print a number between 0,1
print("random number 1-15",random.randint(1,15,6))#prints random number from 1-15 and create a 6*1 matrix
print("2*4*4 matrix with random elements ",random.random((2,4,4)))

list of random 8 numbers [0.35436057 0.36845415 0.28094897 0.63781093 0.51251801 0.86050245
 0.66778398 0.48365255]
number between 0,1 [2.00458973]
random number 1-15 [ 1 13  6 14  6  1]
4*4*2 matrix with random elements  [[[0.55359598 0.95372312 0.25457316 0.13204868]
  [0.42692992 0.73757203 0.15666188 0.45792545]
  [0.13037454 0.08154106 0.68907602 0.06969105]
  [0.47447675 0.08705788 0.64251339 0.4829754 ]]

 [[0.72050813 0.75413386 0.04482004 0.65338421]
  [0.59560895 0.62476521 0.12289828 0.10176437]
  [0.58462316 0.44412124 0.92223273 0.38011117]
  [0.93314324 0.8707616  0.58589892 0.39690744]]]


#### change range of numbers

In [33]:
#change number from 8-12 as 0
a=np.arange(15).reshape(3,5)
a[(a>=8) & (a<=15)]=0
print(a)

[[0 1 2 3 4]
 [5 6 7 0 0]
 [0 0 0 0 0]]


#### create a diagonal matrix

In [35]:
dm=np.diag([1,2,3,4,5,6])#creates a 6*6 diagonal matrix
print(dm)

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


#### Sum of element, sum of rows, sum of columns

In [37]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print("sum of all elements: ",a.sum(axis=None))#prints sum of all elements
print("Sum of columns: ",a.sum(axis=0))#prints sum of columns
print("Sum of rows: ",a.sum(axis=1))#print sum of rows

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
sum of all elements:  78
Sum of columns:  [15 18 21 24]
Sum of rows:  [10 26 42]


#### type casting

In [45]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]],dtype='S')#converts array to string of arrays
print("array: \n",a)
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]],dtype='f')# converts array to float of array
print("array: \n",a)

array: 
 [[b'1' b'2' b'3' b'4']
 [b'5' b'6' b'7' b'8']
 [b'9' b'10' b'11' b'12']]
array: 
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [25]:
b=a[:]
print(b)

[1 2 3 4 5]
