In [1]:
import sklearn
from sklearn import datasets
from sklearn import svm
from sklearn.svm import SVC
import numpy as np
import pandas as pd

#### To load inbuilt iris dataset

In [2]:
iris=datasets.load_iris()#loads the datas into iris variable
iris# prints the data set

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

#### To print the column name

In [3]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


#### to print the dataset in array format

In [4]:
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

#### to find the values they are mapped with

In [5]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


#### To find the names of values in which they are mapped

In [6]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


#### To get to know the description of the datasets

In [7]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

### NOTE: OpenML is an opensource platform for ML

In [8]:
from sklearn.datasets import fetch_openml

In [9]:
mice=fetch_openml(name='miceprotein',version=4)
mice

{'data': array([[0.50364388, 0.74719322, 0.4301753 , ..., 0.13179003, 0.1281856 ,
         1.67565235],
        [0.51461708, 0.68906355, 0.41177034, ..., 0.13510297, 0.1311187 ,
         1.74360965],
        [0.50918309, 0.7302468 , 0.41830878, ..., 0.13336183, 0.12743108,
         1.92642659],
        ...,
        [0.22869955, 0.39517937, 0.23411809, ..., 0.22919311, 0.35521305,
         1.43082502],
        [0.22124241, 0.41289438, 0.24397413, ..., 0.25131651, 0.36535319,
         1.40403123],
        [0.30262572, 0.46105919, 0.25656431, ..., 0.25299481, 0.36527803,
         1.37099946]]),
 'target': array(['c-CS-m', 'c-CS-m', 'c-CS-m', ..., 't-SC-s', 't-SC-s', 't-SC-s'],
       dtype=object),
 'feature_names': ['DYRK1A_N',
  'ITSN1_N',
  'BDNF_N',
  'NR1_N',
  'NR2A_N',
  'pAKT_N',
  'pBRAF_N',
  'pCAMKII_N',
  'pCREB_N',
  'pELK_N',
  'pERK_N',
  'pJNK_N',
  'PKCA_N',
  'pMEK_N',
  'pNR1_N',
  'pNR2A_N',
  'pNR2B_N',
  'pPKCAB_N',
  'pRSK_N',
  'AKT_N',
  'BRAF_N',
  'CAMKII_N',
  

#### to find the details of the data set

In [10]:
mice.details

{'id': '40966',
 'name': 'MiceProtein',
 'version': '4',
 'format': 'ARFF',
 'upload_date': '2017-11-08T16:00:15',
 'licence': 'Public',
 'url': 'https://www.openml.org/data/v1/download/17928620/MiceProtein.arff',
 'file_id': '17928620',
 'default_target_attribute': 'class',
 'row_id_attribute': 'MouseID',
 'ignore_attribute': ['Genotype', 'Treatment', 'Behavior'],
 'tag': ['OpenML-CC18', 'study_135', 'study_98', 'study_99'],
 'visibility': 'public',
 'status': 'active',
 'processing_date': '2018-10-04 00:49:58',
 'md5_checksum': '3c479a6885bfa0438971388283a1ce32'}

#### get a csv file stored in your device

In [11]:
#note: I got this dataset from kaggle

seed=pd.read_csv(r"C:\Users\Priya\Desktop\python files\Seed_Data.csv")#read the file
seed.head()#prints first few elements of the table

A      P       C     LK     WK  A_Coef    LKG  target
0  15.26  14.84  0.8710  5.763  3.312   2.221  5.220       0
1  14.88  14.57  0.8811  5.554  3.333   1.018  4.956       0
2  14.29  14.09  0.9050  5.291  3.337   2.699  4.825       0
3  13.84  13.94  0.8955  5.324  3.379   2.259  4.805       0
4  16.14  14.99  0.9034  5.658  3.562   1.355  5.175       0

#### to know the properties of the dataset

In [12]:
seed.describe

<bound method NDFrame.describe of          A      P       C     LK     WK  A_Coef    LKG  target
0    15.26  14.84  0.8710  5.763  3.312   2.221  5.220       0
1    14.88  14.57  0.8811  5.554  3.333   1.018  4.956       0
2    14.29  14.09  0.9050  5.291  3.337   2.699  4.825       0
3    13.84  13.94  0.8955  5.324  3.379   2.259  4.805       0
4    16.14  14.99  0.9034  5.658  3.562   1.355  5.175       0
..     ...    ...     ...    ...    ...     ...    ...     ...
205  12.19  13.20  0.8783  5.137  2.981   3.631  4.870       2
206  11.23  12.88  0.8511  5.140  2.795   4.325  5.003       2
207  13.20  13.66  0.8883  5.236  3.232   8.315  5.056       2
208  11.84  13.21  0.8521  5.175  2.836   3.598  5.044       2
209  12.30  13.34  0.8684  5.243  2.974   5.637  5.063       2

[210 rows x 8 columns]>

#### To store first few colums of the dataset

In [13]:
x=seed.iloc[:,0:7]
y=seed.iloc[:,7]


### working with svc

#### SVC is a supervised classifier as we supply labeled data
#### it comes wih the pest or optimal seperating boundary(hyper plane), that classifies new unseen examples.

In [14]:
from sklearn.model_selection import train_test_split
#importing this module to internally split the datasets for training and testing.

In [15]:
# spliting the datas for training and testing
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=13)
#test size=0.25 => 25% of total data is used for testing
# random_state =13, it is used to randomly generate and seed the values.
# note: x and y are extrated from the main dataset, ref: cell[13]

In [16]:
# using the standard scaler from sklearn preprocessing
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler 

In [17]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
clf=svm.SVC()
clf.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [18]:
predict=clf.predict(x_test)
#predicting

In [19]:
#predict the accuracy
sklearn.metrics.accuracy_score(y_test,predict)

0.9523809523809523

#### Pipeline and min max scaler

In [20]:
# we will work with iris dataset
iris#ref: cell[2]

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [21]:
#importing minmaxscaler
from sklearn.preprocessing import MinMaxScaler
#MinMaxScaler: the estimator scales and transforms datas individually such that it is in the given range of the tarining set

In [22]:
from sklearn.linear_model import LogisticRegression #import regression
from sklearn.pipeline import Pipeline# import pipeline

In [23]:
# split datas for training and tesing using trainind_test_split
a_train,a_test,b_train,b_test=train_test_split(iris.data,iris.target,test_size=0.2,random_state=40)

In [24]:
# now creating pipeline
pipe_learn=Pipeline([('MinMax',MinMaxScaler()),('log_reg',LogisticRegression())])
#taining pipeline datas
pipe_learn.fit(a_train,b_train)

C:\Users\Priya\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Priya\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


Pipeline(memory=None,
         steps=[('MinMax', MinMaxScaler(copy=True, feature_range=(0, 1))),
                ('log_reg',
                 LogisticRegression(C=1.0, class_weight=None, dual=False,
                                    fit_intercept=True, intercept_scaling=1,
                                    l1_ratio=None, max_iter=100,
                                    multi_class='warn', n_jobs=None,
                                    penalty='l2', random_state=None,
                                    solver='warn', tol=0.0001, verbose=0,
                                    warm_start=False))],
         verbose=False)

In [25]:
accuracy=pipe_learn.score(a_test,b_test)
accuracy

0.9

#### Tuning Hyperparameter

In [26]:
#In machine learning, hyperparameter optimization or tuning is the problem of choosing a set of optimal hyperparameters 
#for a learning algorithm. A hyperparameter is a parameter whose value is used to control the learning process.


In [27]:
#random forest clasifier - they operate by operating multitude of deciion trees at training time and outputting the classes
# that the mode of the classes or the mean prediction of the decision tree.
from sklearn.ensemble import RandomForestClassifier

In [28]:
#Note: using the name iris dataset
# splitting the datas for training and testing
u_train,u_test,v_train,v_test=train_test_split(iris.data,iris.target,test_size=0.2,random_state=30)
# calling the classifier
# cf=RandomForestClassifier() can be called like this but using parameters
cf=RandomForestClassifier(n_estimators=2,min_samples_split=3,min_samples_leaf=2)
#n_estimators tells how many decision trees it should consider
# min_sample_split specifies the minimum number of samples required to split an internal node,by default it is 2
#min_samples_leaf specifies the minimum number of samples required to be at a leaf node. Its default value is 1

In [29]:
# Fiting data into classifier
cf.fit(u_train,v_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=2, min_samples_split=3,
                       min_weight_fraction_leaf=0.0, n_estimators=2,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [30]:
# predicting the values using predict method
pred=cf.predict(u_test)
# testing the accuracy
sklearn.metrics.accuracy_score(v_test,pred)

0.9333333333333333

In [31]:
# in order ro improve the accuracy we can use gridsearch
from sklearn.model_selection import GridSearchCV

In [32]:
# now we have to give parameter grid, what it does is, it selects and tries out the combinations in it
parameter_grid={'n_estimators':[2,5,10,20],'min_samples_split':[2,3],'min_samples_leaf':[1,2,3]}
# n_estimator is 2 previously ref: cell[28], now giving values like 5,10,20 to improve accuracy
#min_samples_split was initially 3 ref: cell[28], now giving value 3 to improve accuracy
#min_samples_leaf was initially 2 ref: cell[28], now giving value 1,3 to improve accuracy

# totally there are 4 options for estimator,2 for sample split, 3 for sample leaf; thus there are totally 24 combinations. 

In [33]:
gridsr=GridSearchCV(estimator=cf,param_grid=parameter_grid)
#fitting data
gridsr.fit(u_train,v_train)

C:\Users\Priya\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\Priya\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=2,
                                              min_samples_split=3,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=2, n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                                              warm_start=False),
             iid

In [34]:
# to check which is the best combination to improve the accuracy
gridsr.best_params_

{'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 20}

In [40]:
# now checking the accuracy again using the given parameters
c=RandomForestClassifier(n_estimators=20,min_samples_split=2,min_samples_leaf=2)
c.fit(u_train,v_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=2, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [41]:
pred=c.predict(u_test)
sklearn.metrics.accuracy_score(v_test,pred)

0.9333333333333333